//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersion("3.0.1")]
[assembly: System.Reflection.AssemblyFileVersion("3.0.1631.29519")]
[assembly: System.Reflection.AssemblyInformationalVersion("3.0.1")]


